name: Deploy WordPress Theme 

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Theme to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: 18.184.245.68
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            scp -r Es.2-tws/thewave-theme ec2-user@18.184.245.68:/var/www/html/wp-content/themes/ 
