name: Deploy WordPress Theme 

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Theme to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: 18.184.245.68
          username: ec2-user
          key: -----BEGIN RSA PRIVATE KEY-----
GltL4SgcWq7xfCGHcS6yTzCgur75oUrk9wv1M+3cqWjuv50P9sQRh+aojtIPRRA6
3L9i3Z+xfEG/PpWeKblO7ZnMjs/554Hs/UFZMN4BBYvc970ly78cf430AIjC/prb
2lmCjhZLIHVQ6uTeheAXQUQAncNlMPOHgmHyFCu9mw/fM5ygAE7y8BEM6rbP0qov
ldKYiDvOzwvfXzVFOB7gut2X8uTlpOyOLKI7JtaSNJyAarjcUe2BM9PMKE96v0sU
ikqN6/LsAaOffsmOXdYlvqgn9nJtGgIgqlsgj0mBSIfGHLypZEou5J/ZGy/VQELR
sVNgO2OBdi4OjhArk77dVXMKzUJG/pGfvtZTWeNFFeUMHveIIWnNOS1ogx8Ianxi
WPptZlAWQanUTcZhCkmGA1vaxEoXCKNQ6FEPfIWI3KBmypFjOc2ZbAsCEnP9XR8v
qx3t3UvjyWA3LQFcKH3AFd1OhPAecp+9dXvtNzRJJwRWkHrvAZTQHrLcIa0yLUMJ
01OqtKgvT8MkmGkj3FN3Ja4PC1phySQYUfDEaFwTiMWnMq/qGcUnKxEwfNFKKQ3T
N3CIqiEzi6kK/fIvZNUq9fhoxYqz9jpeh2dXZJcqO7b3/fWP29xtoBu8+BwYu41/
FERKoexC8dFB2V1CLKQIufR+zh+z84uGyaQJ/eFqFTD/yo7rVHMCKscsuxd+Jje9
orq2cSkB3r/+2/8XcAGQiQyulC0rbTVYJra//Sdmf1WW8qlMgpHAnEtLRij1B+I0
WyCphJMhgyj9/Ln+i9/OLwQLbK2/dIcjA4FMmLSscF40TguPqKkWYZXNpw8JG7Bw
Zcd4VFzjVwQuS5cFmyf/5znyolcIdnadpXuBlwIHdK0b9RWCMzwsRal0A6Mn3n62
5wNta7AcIHon09TEL3vvoDZCxgj4WT+6qnZFIzA861kBWoL1TpSY2vdUNMvxVGAu
Bbv5l4PNo60s+NinfRFMlpHD8ntTHivT3svqAj+VmOu38ziTNRNjyRUW6rtONXPG
VSXQ2XWBdZSGluEBUGLhw86EvVIQ3Ie6LhJyoBAjwCb0krClzdMQ6+I15Olw6Xa1
t0wE1VJv35eskhSQioTJ6ujCDQA4wlTykiJM7Map8k2mmxd5asHxWpdH43fDoLq2
HMHcPe1clitjOwN59G2tgP501ggXjt+KQKUHtJ6s6eXWxHdC80JV3+ctT9Y4G9VW
DKiAWLCGfJdX9Na5YpMD4rZ4RFa9S/WmGAk7yRi459v0ea4oJ/3K+K+VOp33cHMo
Q71+FyI4bjdDkhmPUt6GswhlnHxBvT7QroCptsuokQ2f6HaxredVOvlE03m0wHkC
+gbyn3cILwW/k6DrdFHIV9HmuHMK9u70uWysxZkR6urhWTBPxsZKmmLov14jJIrj
Bu1xjyZ6qRvbB28eYqliWeRhaTseG7EZ8uwbuCide5H6CwBgPkyjWJe2JMuIHbfg
0LBif1MyOHlqs4mIRhzlrgj/gJ0cDm2UKe0RCeuZGVF99evs0n4kktxJlPnnfa4V
zmHPD6DIP2ieKBS44bQIMFvGRAwsV+w9jr28Njp9O1ofSTJskClkbt6ZmZZsZ2bQ
Qoj7wC90s2LzMN1T49105klQ6jdfcpKyEgd13AkGw7C7zWAN8VoUmK+r68OXu8Eb
X77IoIMt+F9wVmaCLxK+va0BSYZMSyYJRAYeQDtubautoEBuQKiRL+ybs/TY6/5e
QuihsP80DJ/FDKskseYzUl6rOlZwP1P+lBDNcLjvnvKZByCOz+2T1ONO26vbdibC
L/fuhIhgbvyLmYvLc3XqTLe4NBJQnxYPMUd+7p4nUV5wOxWc/dePekeOshBy8w/B
9tHtDA8I6pUBxOGqbAXQULQeCO6eFOoAeTOjASpDl55fbno6AU8KO4C3wbwTLrmv
7DJEpFwpcoGtC0CGMrQwYBuTJXQ5jx5L14ODgE16s/ckGaKrliZej7MD+aGLExsf
G+7WAi0G2DxHq5oOr0CD+ji/yFHikKfSMZADu8LRx7Weaa4iibP5tWGhoSjIQjk7
ttzAGYmtRzUnBLRXXn8UJmfpFuvCozozN3Q9vdyD/gF83cC8Xro1sB4VMoy7md8/
fcli2SgD/l0nHwGc/z/y3lStswvmJerjbjyKrcCeLVe0TK/1slhaaHqfomjenTgJ
G3moZf4buRf6IM2eSif/wTHnWeCAro4n7p6E/CoC+dPKzI8RmBh318r82e7Ey4Q9
1L97q75G0BrsN51q+2lxb7sYv3l/leOZ08fxXTps7+X1A3k8svfklGtiZyvyPS8N
rcTKv+Pz/pGHpVwaHjLaSrSd00NUCPf509TnGWrusfMbu8xI/Cm70TsrWPnzgdxD
xwHpQSt2yUUot0bDFVOLC++IsGbbens9P4ASC8nKy3mVfI3Qm2k7Yten1KpVhY3n
M1mM/6iL6kP4Bqdcx4wb/CRQ8eJyeX/bKQrhPko0z+ytp67fYoI7xqnrNKx4tzbc
C2CHBzZbMo+9Kk/vu5Bq0+0eK3h35e/1554iEw0npI8v1b5SmspzpweAOqFlJaFs
muh071xmv82iz+Etz1RUexFjtc3n6UeslpBljTFGxoM+V6hZ76r3YgLDtldVxVro
OHqFkf8AL5O6j/la0gVknPoz/jHiDklApNGX/5W/hytBbXbiMSkWi+/WuTy0utdA
Z3OqerYqyq1YfwqQmT/+x7J6hn0Fw5dj/7UndTIIMn86cg7iUQCf6AXd0a74aTg/
soOapbqJmOXMq+b2VAyPpaoRsJyWlZlQ1vfAN5pQ19mQ+cnU/JGbcM6qDOxKJ5ax
WfUwCjBzj6jc2UldoRiJLbqVyYSpfMGV867aiGbwem82KW8V137K8UjL3U5ybd6Y
L/GIWpACJrxDWl2y+PnKSFWaWK496ePKrOU+LzRkPgSIYiFAi4PPPlzvC8OeH+0J
4CDn80U7j36IiO3cd8LNYsxKcIxnh1EPD1sCBukX6iPQ1VBEqrf4vLYQd+S/BWvy
PcsOm9dIn61A2ixEPmNN3KJPoMjKDWYlM2YupU+SdVL9/AxXgBdhAehlonNTJUg8
TpJfSKcEOjCKqppHWh5FOFXTnHCq5wsiAWiZgjLsaXXM8LrGeLLfkj1uf704+mw9
ttzAGYmtRzUnBLRXXn8UJmfpFuvCozozN3Q9vdyD/gF83cC8Xro1sB4VMoy7md8/
fcli2SgD/l0nHwGc/z/y3lStswvmJerjbjyKrcCeLVe0TK/1slhaaHqfomjenTgJ
G3moZf4buRf6IM2eSif/wTHnWeCAro4n7p6E/CoC+dPKzI8RmBh318r82e7Ey4Q9
1L97q75G0BrsN51q+2lxb7sYv3l/leOZ08fxXTps7+X1A3k8svfklGtiZyvyPS8N
rcTKv+Pz/pGHpVwaHjLaSrSd00NUCPf509TnGWrusfMbu8xI/Cm70TsrWPnzgdxD
xwHpQSt2yUUot0bDFVOLC++IsGbbens9P4ASC8nKy3mVfI3Qm2k7Yten1KpVhY3n
M1mM/6iL6kP4Bqdcx4wb/CRQ8eJyeX/bKQrhPko0z+ytp67fYoI7xqnrNKx4tzbc
C2CHBzZbMo+9Kk/vu5Bq0+0eK3h35e/1554iEw0npI8v1b5SmspzpweAOqFlJaFs
muh071xmv82iz+Etz1RUexFjtc3n6UeslpBljTFGxoM+V6hZ76r3YgLDtldVxVro
OHqFkf8AL5O6j/la0gVknPoz/jHiDklApNGX/5W/hytBbXbiMSkWi+/WuTy0utdA
Z3OqerYqyq1YfwqQmT/+x7J6hn0Fw5dj/7UndTIIMn86cg7iUQCf6AXd0a74aTg/
soOapbqJmOXMq+b2VAyPpaoRsJyWlZlQ1vfAN5pQ19mQ+cnU/JGbcM6qDOxKJ5ax
WfUwCjBzj6jc2UldoRiJLbqVyYSpfMGV867aiGbwem82KW8V137K8UjL3U5ybd6Y
L/GIWpACJrxDWl2y+PnKSFWaWK496ePKrOU+LzRkPgSIYiFAi4PPPlzvC8OeH+0J
4CDn80U7j36IiO3cd8LNYsxKcIxnh1EPD1sCBukX6iPQ1VBEqrf4vLYQd+S/BWvy
PcsOm9dIn61A2ixEPmNN3KJPoMjKDWYlM2YupU+SdVL9/AxXgBdhAehlonNTJUg8
TpJfSKcEOjCKqppHWh5FOFXTnHCq5wsiAWiZgjLsaXXM8LrGeLLfkj1uf704+mw9
-----END RSA PRIVATE KEY-----
          port: 22
          script: |
            scp -r Es.2-tws/thewave-theme ec2-user@18.184.245.68:/var/www/html/wp-content/themes/
 
